### ISSUE TITLE
Sorry dude, I think I DoS'd your codepad...

### ISSUE THREAD

**Issue by raincoats** [Viper-7/Deployable-PHP-Codepad#7]
I was just playing around with shell_exec (no bad intent, just looking around, looked pretty safe actually, I was impressed). Then I got the bright idea to do the following:

while true; do cat /dev/zero > /dev/null; done

I didn't think that would work but... well.. I couldn't access the site for like 10 minutes. So I'm just telling you here because it's probably something you could fix pretty easy, and it can cause a lot of annoyance (sorry again).

**Comment by Viper-7** [comment]
No worries, that _should_ be killed now, however even back then, it only became inaccessable for you (because of PHP's session locking), not everyone else ;)
